
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 24 02:09:07 MDT 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Largo = 48;
  public static final int Entero = 3;
  public static final int Y = 12;
  public static final int cierraLlave = 26;
  public static final int agrupacionIzquierda = 22;
  public static final int abreCorchete = 27;
  public static final int NumeroFlotante = 31;
  public static final int abreLlave = 25;
  public static final int O = 13;
  public static final int Clase = 43;
  public static final int Diferente = 18;
  public static final int Menor = 16;
  public static final int Ruta = 53;
  public static final int Equivale = 17;
  public static final int Posicion = 52;
  public static final int ErrorNumero = 32;
  public static final int Doble = 44;
  public static final int Ingresa = 54;
  public static final int Mayor = 15;
  public static final int Booleano = 39;
  public static final int cierraCorchete = 28;
  public static final int agrupacionDerecha = 23;
  public static final int Retornar = 45;
  public static final int PalabrasR = 35;
  public static final int No = 14;
  public static final int Division = 11;
  public static final int Flotante = 38;
  public static final int Cadena = 42;
  public static final int Falso = 41;
  public static final int Fin = 37;
  public static final int ErrorIdentificador = 34;
  public static final int EOF = 0;
  public static final int DosPuntos = 24;
  public static final int Tamaño = 47;
  public static final int error = 1;
  public static final int Funcion = 51;
  public static final int Imagen = 46;
  public static final int ERROR = 33;
  public static final int MenorIgual = 20;
  public static final int Imprime = 55;
  public static final int Inicio = 2;
  public static final int Ancho = 49;
  public static final int Identificador = 29;
  public static final int Si = 4;
  public static final int Resta = 9;
  public static final int finSentencia = 21;
  public static final int MayorIgual = 19;
  public static final int Sino = 5;
  public static final int Mientras = 6;
  public static final int Declarar = 36;
  public static final int Verdadero = 40;
  public static final int Multiplicacion = 10;
  public static final int Numero = 30;
  public static final int Suma = 8;
  public static final int C_Cadena = 50;
  public static final int Igual = 7;
}

